# Generated by Django 5.2.13 on 2026-04-30 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('archived', 'Archived')], default='pending', max_length=10)),
                ('invite_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('residence_country', models.CharField(blank=True, max_length=2, null=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_couple',
            },
        ),
        migrations.CreateModel(
            name='OnboardingResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_name_backgrounds', models.JSONField(default=list)),
                ('preferred_name_age', models.CharField(choices=[('new', 'New'), ('old', 'Old'), ('balanced', 'Balanced')], max_length=10)),
                ('baby_gender_preference', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('non_binary', 'Non-binary')], max_length=10)),
                ('preferred_name_length', models.CharField(choices=[('short', 'Short'), ('long', 'Long'), ('any', 'Any')], max_length=10)),
                ('historical_importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_responses', to='core.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_onboarding_response',
            },
        ),
        migrations.AddIndex(
            model_name='couple',
            index=models.Index(fields=['status'], name='idx_couple_status'),
        ),
        migrations.AddConstraint(
            model_name='couple',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='unique_couple_pair'),
        ),
    ]
