# Generated by Django 5.2.13 on 2026-04-30 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_couple_and_onboarding_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('gender_usage', models.JSONField(default=list)),
                ('origin_backgrounds', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('scripts', models.JSONField(default=list)),
                ('variants', models.JSONField(default=list)),
                ('length_category', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], max_length=10)),
                ('age_style_category', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('timeless', 'Timeless')], max_length=10)),
                ('historical_significance_score', models.FloatField(default=0.0)),
                ('semantic_summary', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_name',
                'indexes': [models.Index(fields=['active'], name='idx_name_active'), models.Index(fields=['canonical_name'], name='idx_name_canonical')],
                'constraints': [models.UniqueConstraint(fields=('canonical_name',), name='unique_canonical_name')],
            },
        ),
        migrations.CreateModel(
            name='NameVectorIndexRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qdrant_collection', models.CharField(default='names_global_v1', max_length=100)),
                ('qdrant_point_id', models.UUIDField()),
                ('embedding_version', models.CharField(max_length=20)),
                ('indexed_at', models.DateTimeField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector_ref', to='core.name')),
            ],
            options={
                'db_table': 'core_name_vector_index_ref',
            },
        ),
    ]
