# Generated by Django 5.2.13 on 2026-04-30 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_name_and_vector_index_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationDeck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('best_match', 'Best Match'), ('bridge_names', 'Bridge Names'), ('more_like_this', 'More Like This'), ('wildcard', 'Wildcard'), ('local_fit', 'Local Fit'), ('heritage_first', 'Heritage First'), ('style_first', 'Style First')], default='best_match', max_length=20)),
                ('retrieval_profile_json', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='core.couple')),
            ],
            options={
                'db_table': 'core_recommendation_deck',
            },
        ),
        migrations.CreateModel(
            name='RecommendationDeckItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField()),
                ('retrieval_score', models.FloatField(default=0.0)),
                ('rerank_score', models.FloatField(default=0.0)),
                ('explanation_summary', models.TextField(blank=True, default='')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.recommendationdeck')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_appearances', to='core.name')),
            ],
            options={
                'db_table': 'core_recommendation_deck_item',
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='recommendationdeck',
            index=models.Index(fields=['couple', '-created_at'], name='idx_deck_couple_created'),
        ),
        migrations.AddIndex(
            model_name='recommendationdeckitem',
            index=models.Index(fields=['deck', 'rank'], name='idx_deck_item_rank'),
        ),
    ]
