# Generated by Django 5.2.13 on 2026-04-30 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_recommendation_deck_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('match_strength_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('shortlisted', 'Shortlisted'), ('dismissed', 'Dismissed')], default='active', max_length=15)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.couple')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.name')),
            ],
            options={
                'db_table': 'core_mutual_match',
                'indexes': [models.Index(fields=['couple', 'status'], name='idx_match_couple_status')],
                'constraints': [models.UniqueConstraint(fields=('couple', 'name'), name='unique_match_per_couple_name')],
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('maybe', 'Maybe')], max_length=10)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='core.couple')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='core.name')),
                ('source_deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swipes', to='core.recommendationdeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_swipe',
                'indexes': [models.Index(fields=['couple', 'name'], name='idx_swipe_couple_name'), models.Index(fields=['couple', 'user', 'name'], name='idx_swipe_couple_user_name')],
                'constraints': [models.UniqueConstraint(fields=('couple', 'user', 'name'), name='unique_swipe_per_user_name_couple')],
            },
        ),
    ]
