# Generated by Django 5.2.13 on 2026-04-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_swipe_and_mutual_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='x_2d',
            field=models.FloatField(blank=True, help_text='Precomputed 2D projection x-coordinate', null=True),
        ),
        migrations.AddField(
            model_name='name',
            name='y_2d',
            field=models.FloatField(blank=True, help_text='Precomputed 2D projection y-coordinate', null=True),
        ),
    ]
