# Generated by Django 5.2.13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_name_2d_projections"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTasteVector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("embedding", models.JSONField(default=list)),
                ("swipe_count", models.IntegerField(default=0)),
                ("like_rate", models.FloatField(default=0.0)),
                ("vector_variance", models.FloatField(default=0.0)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("last_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste_vector",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_user_taste_vector",
                "indexes": [
                    models.Index(
                        fields=["confidence_score"],
                        name="idx_taste_vector_confidence",
                    ),
                    models.Index(
                        fields=["last_updated_at"],
                        name="idx_taste_vector_updated",
                    ),
                ],
            },
        ),
    ]
