# Generated by Django 5.2.13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_user_taste_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingresponse",
            name="couple",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_responses",
                to="core.couple",
            ),
        ),
    ]
