# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_onboarding_response_couple_nullable"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="couple",
            constraint=models.CheckConstraint(
                condition=~models.Q(user_a=models.F("user_b")),
                name="couple_users_must_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="couple",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="active"),
                fields=("user_a",),
                name="unique_active_couple_for_user_a",
            ),
        ),
        migrations.AddConstraint(
            model_name="couple",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="active", user_b__isnull=False),
                fields=("user_b",),
                name="unique_active_couple_for_user_b",
            ),
        ),
        migrations.AddConstraint(
            model_name="couple",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="pending"),
                fields=("user_a",),
                name="unique_pending_invite_per_user_a",
            ),
        ),
        migrations.AddConstraint(
            model_name="onboardingresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(couple__isnull=False),
                fields=("user", "couple"),
                name="unique_onboarding_response_per_user_couple",
            ),
        ),
        migrations.AddConstraint(
            model_name="onboardingresponse",
            constraint=models.UniqueConstraint(
                condition=models.Q(couple__isnull=True),
                fields=("user",),
                name="unique_solo_onboarding_response_per_user",
            ),
        ),
    ]
