# Generated by Django 5.2.13 on 2026-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_harden_couple_and_onboarding_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationdeck",
            name="mode",
            field=models.CharField(
                choices=[
                    ("best_match", "Best Match"),
                    ("bridge_names", "Bridge Names"),
                    ("more_like_this", "More Like This"),
                    ("wildcard", "Wildcard"),
                ],
                default="best_match",
                max_length=20,
            ),
        ),
    ]
