# Generated by Django 5.2.13 on 2026-06-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_add_cross_cultural_deck_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="name",
            name="phonetic_profile",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Cached Nova phonetic profile describing how the name sounds. Empty dict means not yet enriched. Shape: {"ipa": "ˈeɪdən", "rhyme": "-aden", "syllables": 2, "stress": "primary on first syllable", "sounds_like": "rhymes with Braden and Jayden; two beats, soft ending", "model": "amazon.nova-lite-v1:0", "generated_at": "2026-06-01T12:00:00Z"}',
            ),
        ),
        migrations.AddField(
            model_name="name",
            name="pronunciation_audio",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Reference to the Polly-generated pronunciation audio stored in S3. Empty dict means no audio has been generated. Shape: {"bucket": "babybase-pronunciation-audio-...", "key": "pronunciations/<name_id>.mp3", "voice": "Joanna", "content_type": "audio/mpeg", "generated_at": "2026-06-01T12:00:00Z"}',
            ),
        ),
    ]
