# Generated by Django 5.2.13 on 2026-06-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_add_phonetic_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationdeck",
            name="mode",
            field=models.CharField(
                choices=[
                    ("best_match", "Best Match"),
                    ("bridge_names", "Bridge Names"),
                    ("more_like_this", "More Like This"),
                    ("wildcard", "Wildcard"),
                    ("cross_cultural", "Names That Travel"),
                    ("sounds_like", "Sounds Like"),
                ],
                default="best_match",
                max_length=20,
            ),
        ),
    ]
