"""Unit and property-based tests for the "Sounds Like" query path (task 5.4).

Covers ``core.services.swipes.get_sounds_like_names``, which anchors on a
name's stored ``phonetic_style`` vector in Qdrant (no query-time embedding) and
returns similar-sounding names, excluding the anchor and the couple's
already-swiped names.

These tests mock the Qdrant network boundary (``get_qdrant_client``) and the
``NameVectorIndexRef``/``Swipe`` managers — mirroring the existing
``test_fetch_vectors_for_name_ids.py`` conventions — so no real database or
Qdrant access is required. The real ``get_similar_to_names`` and ``search_names``
are exercised end to end, so the exclusion guarantees are genuinely verified.

Properties:
- Property 6: no query-time embedding; results exclude the anchor and swiped names.
- Property 7: empty result (never raises) on a missing stored vector or a Qdrant error.
"""

import uuid
from unittest.mock import MagicMock, patch

import httpx
from django.test import override_settings
from hypothesis import given, settings
from hypothesis import strategies as st
from qdrant_client.http.exceptions import UnexpectedResponse

from core.models import NameVectorIndexRef
from core.services.swipes import get_sounds_like_names

# A fixed anchor point id reused across examples. Random uuids generated by the
# strategies below effectively never collide with it.
ANCHOR_POINT_ID = uuid.UUID("11111111-1111-1111-1111-111111111111")

VECTOR_DIM = 1024


# ---------------------------------------------------------------------------
# Lightweight stand-ins for Qdrant point / hit objects
# ---------------------------------------------------------------------------


class _Hit:
    """A minimal stand-in for a Qdrant query hit (id, score, payload)."""

    def __init__(self, point_id, score: float = 0.9):
        self.id = point_id
        self.score = score
        self.payload = {
            "name_id": str(point_id),
            "canonical_name": "Candidate",
            "origin_backgrounds": ["English"],
            "gender_usage": ["girl"],
            "length_category": "short",
            "age_style_category": "classic",
            "active": True,
        }


class _Point:
    """A minimal stand-in for a retrieved Qdrant point with named vectors."""

    def __init__(self, vector):
        self.vector = vector


def _anchor_point(vector_name: str = "phonetic_style") -> _Point:
    """A retrieved anchor point carrying a 1024-dim named vector."""
    return _Point({vector_name: [0.1] * VECTOR_DIM})


def _mock_client(retrieve_return, query_hits):
    """Build a mock Qdrant client for the retrieve + query_points flow."""
    client = MagicMock()
    client.retrieve.return_value = retrieve_return
    client.query_points.return_value.points = query_hits
    return client


def _configure_swipes(mock_swipe, swiped_point_ids):
    """Wire the Swipe manager chain to return the given swiped point ids."""
    chain = mock_swipe.objects.filter.return_value.values_list.return_value
    chain.distinct.return_value = list(swiped_point_ids)


def _configure_index_ref(mock_nvir_objects, point_id=ANCHOR_POINT_ID):
    """Wire NameVectorIndexRef.objects.get to return a ref with ``point_id``."""
    mock_nvir_objects.get.return_value = MagicMock(qdrant_point_id=point_id)


# ===========================================================================
# Property 6: no query-time embedding; excludes the anchor and swiped names
# ===========================================================================

_uuid_list = st.lists(st.uuids(), unique=True, max_size=10)
_swiped_list = st.lists(st.uuids(), unique=True, max_size=5)


# Feature: phonetic-name-search, Property 6
@override_settings(QDRANT_COLLECTION="test_names")
@settings(max_examples=25)
@given(others=_uuid_list, swiped=_swiped_list)
@patch("core.services.embeddings.generate_embeddings_batch")
@patch("core.services.embeddings.generate_embedding")
@patch("core.services.swipes.Swipe")
@patch("core.models.NameVectorIndexRef.objects")
@patch("core.services.qdrant_client.get_qdrant_client")
def test_sounds_like_excludes_anchor_and_swiped_without_embedding(
    mock_get_client,
    mock_nvir_objects,
    mock_swipe,
    mock_generate_embedding,
    mock_generate_embeddings_batch,
    others,
    swiped,
):
    """
    Property 6: For any anchor name and couple, ``get_sounds_like_names`` issues
    no embedding call, and no returned point/name id is the anchor or a name the
    couple already swiped.

    Validates: Requirements 8.2, 8.3
    """
    # Keep the candidate "others" disjoint from the anchor and the swiped set so
    # the surviving ids are unambiguous.
    swiped = [s for s in swiped if s != ANCHOR_POINT_ID]
    swiped_set = set(swiped)
    others = [o for o in others if o != ANCHOR_POINT_ID and o not in swiped_set]

    _configure_index_ref(mock_nvir_objects)
    _configure_swipes(mock_swipe, swiped)

    # Candidates returned by Qdrant deliberately include the anchor and the
    # swiped ids; both must be filtered out of the final result.
    candidate_hits = (
        [_Hit(o) for o in others]
        + [_Hit(ANCHOR_POINT_ID)]
        + [_Hit(s) for s in swiped]
    )
    mock_get_client.return_value = _mock_client([_anchor_point()], candidate_hits)

    couple = MagicMock(name="couple")
    results = get_sounds_like_names(str(uuid.uuid4()), couple)

    returned_point_ids = {r["point_id"] for r in results}
    returned_name_ids = {r["name_id"] for r in results}

    # No query-time embedding was generated — the anchor vector came from storage.
    mock_generate_embedding.assert_not_called()
    mock_generate_embeddings_batch.assert_not_called()

    # The anchor is never returned.
    assert str(ANCHOR_POINT_ID) not in returned_point_ids
    assert str(ANCHOR_POINT_ID) not in returned_name_ids

    # No swiped name is returned.
    for s in swiped:
        assert str(s) not in returned_point_ids
        assert str(s) not in returned_name_ids

    # Only genuine, non-excluded candidates survive, capped at 10.
    assert returned_point_ids <= {str(o) for o in others}
    assert len(results) <= 10


@override_settings(QDRANT_COLLECTION="test_names")
@patch("core.services.embeddings.generate_embeddings_batch")
@patch("core.services.embeddings.generate_embedding")
@patch("core.services.swipes.Swipe")
@patch("core.models.NameVectorIndexRef.objects")
@patch("core.services.qdrant_client.get_qdrant_client")
def test_sounds_like_anchors_on_phonetic_style_vector(
    mock_get_client,
    mock_nvir_objects,
    mock_swipe,
    mock_generate_embedding,
    mock_generate_embeddings_batch,
):
    """
    The service retrieves and searches the ``phonetic_style`` named vector — not
    ``semantic`` — and never generates an embedding at query time (Req 8.1, 8.2).

    Feature: phonetic-name-search, Property 6
    """
    _configure_index_ref(mock_nvir_objects)
    _configure_swipes(mock_swipe, [])

    survivor = uuid.uuid4()
    mock_get_client.return_value = _mock_client([_anchor_point()], [_Hit(survivor)])

    results = get_sounds_like_names(str(uuid.uuid4()), MagicMock())

    # Anchor vector fetched from storage under the phonetic_style named vector.
    mock_get_client.return_value.retrieve.assert_called_once()
    assert mock_get_client.return_value.retrieve.call_args.kwargs["with_vectors"] == ["phonetic_style"]

    # The nearest-neighbour search uses the phonetic_style vector.
    assert mock_get_client.return_value.query_points.call_args.kwargs["using"] == "phonetic_style"

    # No embedding generation occurred at query time.
    mock_generate_embedding.assert_not_called()
    mock_generate_embeddings_batch.assert_not_called()

    assert [r["point_id"] for r in results] == [str(survivor)]


@override_settings(QDRANT_COLLECTION="test_names")
@patch("core.services.swipes.Swipe")
@patch("core.models.NameVectorIndexRef.objects")
@patch("core.services.qdrant_client.get_qdrant_client")
def test_sounds_like_returns_at_most_ten(mock_get_client, mock_nvir_objects, mock_swipe):
    """The service caps results at 10 even when Qdrant returns more (Req 8.1)."""
    _configure_index_ref(mock_nvir_objects)
    _configure_swipes(mock_swipe, [])

    candidate_hits = [_Hit(uuid.uuid4(), score=1.0 - i / 100) for i in range(25)]
    mock_get_client.return_value = _mock_client([_anchor_point()], candidate_hits)

    results = get_sounds_like_names(str(uuid.uuid4()), MagicMock())

    assert len(results) == 10


# ===========================================================================
# Property 7: missing stored vector / Qdrant error → [] without raising
# ===========================================================================


@patch("core.services.qdrant_client.get_qdrant_client")
@patch("core.models.NameVectorIndexRef.objects")
def test_sounds_like_empty_when_no_index_ref(mock_nvir_objects, mock_get_client):
    """
    A name with no NameVectorIndexRef (no stored vector) yields an empty result
    and never touches Qdrant.

    Feature: phonetic-name-search, Property 7
    Validates: Requirements 8.7, 11.4
    """
    mock_nvir_objects.get.side_effect = NameVectorIndexRef.DoesNotExist()

    results = get_sounds_like_names(str(uuid.uuid4()), MagicMock())

    assert results == []
    mock_get_client.assert_not_called()


@override_settings(QDRANT_COLLECTION="test_names")
@patch("core.services.swipes.Swipe")
@patch("core.models.NameVectorIndexRef.objects")
@patch("core.services.qdrant_client.get_qdrant_client")
def test_sounds_like_empty_when_no_stored_phonetic_vector(
    mock_get_client, mock_nvir_objects, mock_swipe
):
    """
    When the anchor point has no stored ``phonetic_style`` vector, the service
    returns an empty result without raising (Req 8.7, 11.4).

    Feature: phonetic-name-search, Property 7
    """
    _configure_index_ref(mock_nvir_objects)
    _configure_swipes(mock_swipe, [])

    # Retrieved point carries only a semantic vector — no phonetic_style.
    point_without_phonetic = _Point({"semantic": [0.2] * VECTOR_DIM})
    mock_get_client.return_value = _mock_client([point_without_phonetic], [])

    results = get_sounds_like_names(str(uuid.uuid4()), MagicMock())

    assert results == []


def _connection_error() -> Exception:
    return ConnectionError("qdrant connection refused")


def _timeout_error() -> Exception:
    return TimeoutError("qdrant timed out")


def _unexpected_response() -> Exception:
    return UnexpectedResponse(
        status_code=500,
        reason_phrase="Internal Server Error",
        content=b"boom",
        headers=httpx.Headers(),
    )


_QDRANT_ERROR_FACTORIES = [_connection_error, _timeout_error, _unexpected_response]


# Feature: phonetic-name-search, Property 7
@override_settings(QDRANT_COLLECTION="test_names")
@settings(max_examples=30)
@given(error_factory=st.sampled_from(_QDRANT_ERROR_FACTORIES))
@patch("core.services.swipes.Swipe")
@patch("core.models.NameVectorIndexRef.objects")
@patch("core.services.qdrant_client.get_qdrant_client")
def test_sounds_like_empty_when_qdrant_raises(
    mock_get_client, mock_nvir_objects, mock_swipe, error_factory
):
    """
    Property 7: For any anchor name, when Qdrant raises (UnexpectedResponse,
    ConnectionError, or TimeoutError), ``get_sounds_like_names`` returns ``[]``
    without propagating the exception.

    Validates: Requirements 8.7, 11.3, 11.4
    """
    _configure_index_ref(mock_nvir_objects)
    _configure_swipes(mock_swipe, [])

    client = MagicMock()
    client.retrieve.side_effect = error_factory()
    mock_get_client.return_value = client

    results = get_sounds_like_names(str(uuid.uuid4()), MagicMock())

    assert results == []
